### ISSUE TITLE
Version 2.0.1 fails on bedrock start because didio.methods.veres is not a function

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-did-client#10]
veres is undefined in didio.methods by default

```
2019-08-09T19:11:58.689Z - critical: worker: uncaught error: error=TypeError: didio.methods.veres is not a function
    at bedrock.events.on (/node_modules/bedrock-did-client/lib/index.js:32:28)
    at iterate (/node_modules/async-node-events/lib/async-node-events.js:40:27)
```

**Comment by aljones15** [comment]
NOTE: as of August 13 2019 you should not be using this library and all instances of it are being replaced with a simple document loader.
